spring:
  application:
    name: UseService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nb
    password: 654321
    jdbc-url: jdbc:mysql://localhost:3306/signup?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
