spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nb
    password: 654321
    jdbc-url: jdbc:mysql://localhost:3306/signup?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1200
  application:
    name: ContestService
server:
  port: 8080

logging:
  level:
    root: info
    lyw.demo.AOP: DEBUG
