spring:
  application:
    name: SignUpRoot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nb
    password: 654321
    url: jdbc:mysql://localhost:33306/signup?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false

server:
  port: 8071